on: [push]
  name: Azure ARM
  jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:

        # Checkout code
      - uses: actions/checkout@main

        # Log into Azure
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

        # Deploy ARM template
      - name: Run ARM deploy
        uses: azure/arm-deploy@v1
        with:
          scope: tenant        
          template: ./infra-as-code/bicep/modules/managementGroups/managementGroups.bicep
          parameters: ./infra-as-code/bicep/modules/managementGroups/parameters/managementGroups.parameters.all.json
